@port = 3000

### Get all blogs
GET http://localhost:{{port}}/api/blogs

#### Add a blog
POST http://localhost:{{port}}/api/blogs
Content-Type: application/json

{
    "title": "Testing #1",
    "author": "Testing author",
    "url": "some URL",
    "likes": 3

}

#### Remove a blog

DELETE http://localhost:{{port}}/api/blogs/6284ec3caba6f5fc00a65a4d 

#### Update a blog
PUT http://localhost:{{port}}/api/blogs/6284ec3caba6f5fc00a65a4d
Content-Type: application/json

{
    "title": "Testing #2",
    "author": "Jan",
    "url": "new URL",
    "likes": 10
}