@port = 3000

### Get all blogs
GET http://localhost:{{port}}/api/blogs

#### Add a blog
POST http://localhost:{{port}}/api/blogs
Content-Type: application/json

{
    "title": "Testing #1",
    "author": "Testing author",
    "url": "some URL",
    "likes": 3

}