@port = 3003

### Get all blogs
GET http://localhost:{{port}}/api/blogs

#### Add a blog
POST http://localhost:{{port}}/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RpbmciLCJpZCI6IjYyOGE3YTcwMzlkMzQ3NzFkZDU0NWFlNSIsImlhdCI6MTY1MzI0MjQ5MywiZXhwIjoxNjUzMjQ2MDkzfQ.L84IvbHZfwEROcDDajXJMf1uvGQo-2N0vy_h-q7v0Jo
{ 
    "title": "Testing #10 UPDATED",
    "author": "Jan",
    "url": "some URL",
    "likes": 3
}

#### Remove a blog

DELETE http://localhost:{{port}}/api/blogs/628975d16f28581c1126c604
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkphbkphbjIiLCJpZCI6IjYyODk3NTE1NmYyODU4MWMxMTI2YzVmOSIsImlhdCI6MTY1MzE3NzA1MywiZXhwIjoxNjUzMTgwNjUzfQ.6yegFbdUHe-LTMMkXrid1XjEWncw4zE8sQl8lVk2xXw

#### Update a blog
PUT http://localhost:{{port}}/api/blogs/628c0b79b8303db45e1ebcd5
Content-Type: application/json

{
    "title": "Frontend #1",
    "author": "Jan",
    "url": "new URL",
    "likes": 10
}

#### Getting all Users
GET http://localhost:{{port}}/api/user


#### Adding New User
POST http://localhost:{{port}}/api/user
Content-Type: application/json

{
    "username": "Janat",
    "name": "Janat",
    "password": "123456789"
}

#### User Login
POST http://localhost:{{port}}/api/login 
Content-Type: application/json 

{
    "username": "Testing again",
    "password": "12345"
}